services:
    fbeen.simple_cms.routing_loader:
        class: Fbeen\SimpleCmsBundle\Routing\SimpleCmsLoader
        arguments: ['@service_container']
        tags:
            - { name: routing.loader }
            
    fbeen.simple_cms.content_helper:
        class: Fbeen\SimpleCmsBundle\Service\ContentHelper
        arguments: ['@service_container']

    fbeen.simple_cms.route_helper:
        class: Fbeen\SimpleCmsBundle\Service\RouteHelper
        arguments: ['@service_container']

    fbeen.simple_cms.action_listener:
        class: Fbeen\SimpleCmsBundle\EventListener\ActionListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.controller_arguments, method: onKernelRequest, priority: 33 }
            
    fbeen.simple_cms.block_extension:
        class: Fbeen\SimpleCmsBundle\Twig\BlockExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }
            
    fbeen.simple_cms.menu_extension:
        class: Fbeen\SimpleCmsBundle\Twig\MenuExtension
        arguments: ['@knp_menu.helper']
        tags:
            - { name: twig.extension }
    
    fbeen.simple_cms.twig.extension.intl:
        class:        Twig_Extensions_Extension_Intl
        tags:
             - { name: 'twig.extension' }
             
    sonata.block.service.clear_cache:
        class: Fbeen\SimpleCmsBundle\Admin\ClearCacheBlockService
        arguments:
            - "Clear Cache"
            - "@templating"
            - "@service_container"
        tags:
            - { name: sonata.block }

    # blockTypes
    fbeen.simple_cms.blocktype_text_block:
        class: Fbeen\SimpleCmsBundle\Blocks\TextBlock
        arguments: ['@service_container']
    
    fbeen.simple_cms.blocktype_image_block:
        class: Fbeen\SimpleCmsBundle\Blocks\ImageBlock
        arguments: ['@service_container']
    
    fbeen.simple_cms.blocktype_menu_block:
        class: Fbeen\SimpleCmsBundle\Blocks\MenuBlock
        arguments: ['@service_container']
    
    fbeen.simple_cms.blocktype_news_block:
        class: Fbeen\SimpleCmsBundle\Blocks\NewsBlock
        arguments: ['@service_container']
    
    # sonata admin services
    fbeen_simple_cms.admin.route:
        class: Fbeen\SimpleCmsBundle\Admin\RouteAdmin
        arguments: [~, Fbeen\SimpleCmsBundle\Entity\Route, FbeenSimpleCmsBundle:Admin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Routes }

    fbeen_simple_cms.admin.block:
        class: Fbeen\SimpleCmsBundle\Admin\BlockAdmin
        arguments: [~, Fbeen\SimpleCmsBundle\Entity\Block, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Block }

    fbeen_simple_cms.admin.content:
        class: Fbeen\SimpleCmsBundle\Admin\ContentAdmin
        arguments: [~, Fbeen\SimpleCmsBundle\Entity\Content, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Pagina's }

    fbeen_simple_cms.admin.menu:
        class: Fbeen\SimpleCmsBundle\Admin\MenuAdmin
        arguments: [~, Fbeen\SimpleCmsBundle\Entity\Menu, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Menu's }

    fbeen_simple_cms.admin.menuitem:
        class: Fbeen\SimpleCmsBundle\Admin\MenuitemAdmin
        arguments: [~, Fbeen\SimpleCmsBundle\Entity\Menuitem, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Menuitem }

    fbeen_simple_cms.admin.text_block_type:
        class: Fbeen\SimpleCmsBundle\Admin\TextBlockTypeAdmin
        arguments: [~, Fbeen\SimpleCmsBundle\Entity\TextBlockType, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Tekst blokken }

    fbeen_simple_cms.admin.image:
        class: Fbeen\SimpleCmsBundle\Admin\ImageAdmin
        arguments: [~, Fbeen\SimpleCmsBundle\Entity\Image, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Afbeeldingen }

    fbeen_simple_cms.admin.newsitem:
        class: Fbeen\SimpleCmsBundle\Admin\NewsitemAdmin
        arguments: [~, Fbeen\SimpleCmsBundle\Entity\Newsitem, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: "Nieuwsberichten" }
