<?php

namespace Fbeen\SimpleCmsBundle\Repository;

/**
 * BlockContainerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockContainerRepository extends \Doctrine\ORM\EntityRepository
{
}
