<?php

namespace Fbeen\SimpleCmsBundle\Repository;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCompleteContent($name)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT c, t, b FROM FbeenSimpleCmsBundle:Content c
            LEFT JOIN c.translations t
            LEFT JOIN c.blocks b
            WHERE c.name=:name'
        )   ->setParameter('name', $name)
            ->getOneOrNullResult();        
    }
}
