<?php

namespace Fbeen\SimpleCmsBundle\Repository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findImagesWithTag($tagName)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT i, t FROM FbeenSimpleCmsBundle:Image i
            JOIN i.tags t
            WHERE t.name=:name'
        )   ->setParameter('name', $tagName)
            ->getResult();        
    }
}
