<?php

namespace Fbeen\SimpleCmsBundle\Repository;

/**
 * ImageTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageTagRepository extends \Doctrine\ORM\EntityRepository
{
    public function findImagesWithTag($tagName)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT t, i FROM FbeenSimpleCmsBundle:ImageTag t
            JOIN t.images i
            WHERE t.name=:name'
        )   ->setParameter('name', $tagName)
            ->getOneOrNullResult();        
    }
}
