<?php

namespace Fbeen\SimpleCmsBundle\Repository;

/**
 * NewsitemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsitemRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllActive() {
        return $this->getEntityManager()->createQuery(
            'SELECT n FROM FbeenSimpleCmsBundle:Newsitem n
            WHERE (n.publishAble > 0 AND CURRENT_DATE() BETWEEN n.publishFrom AND n.publishUntil) OR 
            (n.publishAble > 0 AND n.publishFrom is NULL AND CURRENT_DATE() <= n.publishUntil) OR
            (n.publishAble > 0 AND CURRENT_DATE() >= n.publishFrom AND n.publishUntil is NULL) OR
            (n.publishAble > 0 AND n.publishFrom is NULL AND n.publishUntil is NULL)
            ORDER BY n.id DESC'
        );
    }
    
    public function findFrontpageNews() {
        return $this->getEntityManager()->createQuery(
            'SELECT n FROM FbeenSimpleCmsBundle:Newsitem n
            WHERE 
            n.showOnFrontpage > 0 AND (
                (n.publishAble > 0 AND CURRENT_DATE() BETWEEN n.publishFrom AND n.publishUntil) OR 
                (n.publishAble > 0 AND n.publishFrom is NULL AND CURRENT_DATE() <= n.publishUntil) OR
                (n.publishAble > 0 AND CURRENT_DATE() >= n.publishFrom AND n.publishUntil is NULL) OR
                (n.publishAble > 0 AND n.publishFrom is NULL AND n.publishUntil is NULL)
            )
            ORDER BY n.id DESC'
        );
    }
}
