<?php

namespace Fbeen\SimpleCmsBundle\Repository;

/**
 * SimpleBlockTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SimpleBlockTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
